In [17]:
import yfinance as yf
data = yf.download(tickers='AAPL', period='5d', interval='15m')
data.head(10)

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2024-08-05 09:30:00,199.000000,210.000000,198.229996,208.550003,208.550003,27409767
2024-08-05 09:45:00,208.500000,211.110001,207.169998,207.630005,207.630005,7244950
2024-08-05 10:00:00,209.214996,211.009995,208.410004,209.789993,209.789993,4714621
2024-08-05 10:15:00,209.740005,211.000000,207.699997,207.978699,207.978699,3988021
2024-08-05 10:30:00,207.940704,210.399994,207.820007,208.497101,208.497101,3526116
2024-08-05 10:45:00,208.539993,210.380005,208.000000,209.559906,209.559906,2713821
2024-08-05 11:00:00,209.585007,212.949905,208.740005,212.259995,212.259995,4297761
2024-08-05 11:15:00,212.389999,213.470001,211.169998,211.169998,211.169998,2866456
2024-08-05 11:30:00,211.199997,211.888000,209.919998,210.100006,210.100006,2745094
2024-08-05 11:45:00,210.100006,211.330002,209.505005,210.335007,210.335007,2402537

In [13]:
from src.indicators import get_indicators

data = get_indicators(data)
# data.dropna(inplace=True)
data

/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:68: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #         ep = low[0]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:69: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #         psar[0] = High[0]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:74: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                 if low[i] < psar[i]:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:77: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     psar[i] = High[i]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:78: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     ep = low[i]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:81: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                 if High[i] > psar[i]:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:84: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     psar[i] = low[i]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:85: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     ep = High[i]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:89: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     if High[i] > ep:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:90: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                         ep = High[i]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     if low[i - 1] < psar[i]:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:93: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                         psar[i] = low[i - 1]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:94: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     if low[i - 2] < psar[i]:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:95: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                         psar[i] = low[i - 2]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:97: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     if low[i] < ep:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:98: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                         ep = low[i]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:100: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     if High[i - 1] > psar[i]:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:101: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                         psar[i] = High[i - 1]
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:102: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                     if High[i - 2] > psar[i]:
/Users/pkodesia/Documents/p_workspace/algo-bot/src/indicators.py:103: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  #                         psar[i] = High[i - 2]

,Open,High,Low,Close,Adj Close,Volume,ema_200,ema_9,ema_21,ema_55,...,long_stop,short_stop,stddev,upper_rvi,lower_rvi,rvi,obv,mf_mult,mf_vol,cmf
Datetime,,,,,,,,,,,,,,,,,,,,,
2024-08-09 09:30:00,212.080002,213.479996,211.979996,212.259995,212.259995,3212120,NaN,NaN,NaN,NaN,...,210.704996,214.754996,NaN,NaN,NaN,NaN,3212120,-0.626668,-2.012934e+06,NaN
2024-08-09 09:45:00,212.270004,213.300003,212.240005,212.529999,212.529999,1565613,NaN,NaN,NaN,NaN,...,211.339008,214.201001,NaN,NaN,NaN,NaN,4777733,-0.452842,-7.089747e+05,NaN
2024-08-09 10:00:00,212.580002,214.490005,212.339996,214.387100,214.387100,1614260,NaN,NaN,NaN,NaN,...,210.512489,216.317513,NaN,NaN,NaN,NaN,6391993,0.904275,1.459734e+06,NaN
2024-08-09 10:15:00,214.369995,214.789505,214.020004,214.699997,214.699997,1375537,NaN,NaN,NaN,NaN,...,213.365929,215.443581,NaN,NaN,NaN,NaN,7767530,0.767361,1.055533e+06,NaN
2024-08-09 10:30:00,214.710007,214.755005,213.669998,213.830002,213.830002,1253790,NaN,NaN,NaN,NaN,...,212.747742,215.677261,NaN,NaN,NaN,NaN,6513740,-0.705064,-8.840024e+05,NaN
2024-08-09 10:45:00,213.790100,215.179993,213.760300,214.764999,214.764999,1379938,NaN,NaN,NaN,NaN,...,212.553561,216.386732,NaN,NaN,NaN,NaN,7893678,0.415376,5.731932e+05,NaN
2024-08-09 11:00:00,214.820007,215.520004,214.804993,215.210007,215.210007,1168644,NaN,NaN,NaN,NaN,...,214.123245,216.201752,NaN,NaN,NaN,NaN,9062322,0.132888,1.552988e+05,NaN
2024-08-09 11:15:00,215.220001,215.735001,215.100006,215.134995,215.134995,1050616,NaN,NaN,NaN,NaN,...,214.560261,216.274746,NaN,NaN,NaN,NaN,8011706,-0.889799,-9.348374e+05,NaN
2024-08-09 11:30:00,215.119995,215.710007,215.059998,215.110001,215.110001,1052451,NaN,214.335479,NaN,NaN,...,214.507490,216.262514,NaN,NaN,NaN,NaN,6959255,-0.846147,-8.905279e+05,NaN
2024-08-09 11:45:00,215.115005,215.449997,214.540100,214.710007,214.710007,845636,NaN,214.410385,NaN,NaN,...,213.766688,216.223409,NaN,NaN,NaN,NaN,6113619,-0.626537,-5.298218e+05,NaN
2024-08-09 12:00:00,214.699997,214.899994,214.410004,214.539993,214.539993,847615,NaN,214.436306,NaN,NaN,...,213.993512,215.316486,NaN,NaN,NaN,NaN,5266004,-0.469420,-3.978870e+05,NaN
2024-08-09 12:15:00,214.544998,214.910004,214.460007,214.530106,214.530106,1247836,NaN,214.455066,NaN,NaN,...,214.077509,215.292501,0.970396,NaN,NaN,NaN,4018168,-0.688447,-8.590694e+05,NaN
2024-08-09 12:30:00,214.529999,214.929504,214.510101,214.850006,214.850006,701982,NaN,214.534054,NaN,NaN,...,214.153609,215.285997,0.731993,NaN,NaN,NaN,4720150,0.620898,4.358592e+05,NaN
2024-08-09 12:45:00,214.850006,215.449997,214.710007,215.434998,215.434998,1104051,NaN,214.714243,NaN,NaN,...,214.081015,216.078989,0.430657,NaN,NaN,NaN,5824201,0.959461,1.059293e+06,NaN
2024-08-09 13:00:00,215.438202,215.860001,215.250000,215.850006,215.850006,743454,NaN,214.941396,NaN,NaN,...,214.731499,216.378501,0.512639,NaN,NaN,NaN,6567655,0.967231,7.190919e+05,NaN
2024-08-09 13:15:00,215.830002,216.539993,215.830002,216.535004,216.535004,1256672,NaN,215.260117,NaN,NaN,...,215.226509,217.143486,0.693127,NaN,NaN,NaN,7824327,0.985945,1.239009e+06,NaN
2024-08-09 13:30:00,216.539993,216.779999,216.175003,216.257797,216.257797,1003281,NaN,215.459653,NaN,NaN,...,215.660757,217.294245,0.660873,NaN,NaN,NaN,6821046,-0.726298,-7.286813e+05,NaN
2024-08-09 13:45:00,216.270004,216.419998,215.639999,215.916397,215.916397,814528,NaN,215.551002,NaN,NaN,...,214.977000,217.082997,0.668547,NaN,NaN,NaN,6006518,-0.291287,-2.372613e+05,NaN
2024-08-09 14:00:00,215.929993,216.091507,215.289993,215.410004,215.410004,822474,NaN,215.522802,NaN,NaN,...,214.608707,216.772794,0.667505,NaN,NaN,NaN,5184044,-0.700541,-5.761765e+05,NaN
2024-08-09 14:15:00,215.419998,215.509995,214.919998,215.279999,215.279999,891084,NaN,215.474242,NaN,NaN,...,214.418501,216.011491,0.664434,NaN,NaN,NaN,4292960,0.220349,1.963491e+05,NaN
2024-08-09 14:30:00,215.274994,215.507095,214.899994,215.285004,215.285004,826784,NaN,215.436394,214.845352,NaN,...,214.383958,216.023132,0.660146,NaN,NaN,NaN,5119744,0.268354,2.218708e+05,NaN
2024-08-09 14:45:00,215.309998,215.675003,215.039993,215.610001,215.610001,1230077,NaN,215.471115,214.914866,NaN,...,214.500235,216.214761,0.626994,NaN,NaN,NaN,6349821,0.795271,9.782446e+05,NaN
2024-08-09 15:00:00,215.604996,216.080002,215.210007,215.919998,215.919998,1058922,NaN,215.560892,215.006241,NaN,...,214.470511,216.819498,0.566936,NaN,NaN,NaN,7408743,0.632173,6.694223e+05,NaN
2024-08-09 15:15:00,215.940002,216.380005,215.649994,216.285004,216.285004,1110508,NaN,215.705714,215.122493,NaN,...,215.029485,217.000514,0.495185,NaN,NaN,NaN,8519251,0.739727,8.214723e+05,NaN
2024-08-09 15:30:00,216.259995,216.615005,216.100006,216.250000,216.250000,1440157,NaN,215.814571,215.224993,NaN,...,215.662257,217.052755,0.432679,NaN,NaN,NaN,7079094,-0.417499,-6.012637e+05,NaN
2024-08-09 15:45:00,216.250000,216.600006,215.339996,216.300003,216.300003,3798561,NaN,215.911658,215.322721,NaN,...,214.268988,217.671014,0.431819,NaN,NaN,NaN,10877655,0.523808,1.989718e+06,NaN

In [14]:
from src.data.nifty_list import nifty50_companies
print(nifty50_companies.keys())

dict_keys(['ADANIENT', 'ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK', 'INFY', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'ULTRACEMCO', 'UPL', 'WIPRO'])